[package]
name = "orbit"
version = "0.1.0"
edition = "2024"

[dependencies]
orbit-dbus = { path = "../../src/orbit-dbus/" }
clap = { version = "4.5.49", features = ["derive"] }
zbus = { version = "5.12.0", features = ["blocking-api"] }
